# Generated by Django 4.2.13 on 2024-06-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(default='Enter Customer Name', max_length=200),
        ),
    ]
