# Generated by Django 4.2.13 on 2024-06-21 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_inventoryitem_customer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='customer_name',
        ),
    ]
