# Generated by Django 4.2.13 on 2024-07-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_inventoryitem_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='built_by',
            field=models.CharField(default='Enter Builder Name...', max_length=200),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='date_built',
            field=models.CharField(default='MM/DD/YYYY', max_length=10),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='complaint',
            field=models.TextField(default='Enter Complaint...', max_length=2000),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='date_complained',
            field=models.CharField(default='MM/DD/YYYY', max_length=10),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(default='Enter Customer Name...', max_length=200),
        ),
    ]
