# Generated by Django 4.2.13 on 2024-07-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventoryitem_built_by_inventoryitem_date_built_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
