# Generated by Django 4.2.13 on 2024-07-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_inventoryitem_built_by_delete_builder'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
