# Generated by Django 4.2.13 on 2024-07-05 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_inventoryitem_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='cost',
        ),
    ]
