# Generated by Django 4.2.13 on 2024-07-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_inventoryitem_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('waiting', 'Waiting'), ('closed', 'Closed')], default='new', max_length=20),
        ),
    ]
