# Generated by Django 4.2.13 on 2024-08-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_order_ordercustomer_product_orderitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='9b6a7f614698', editable=False, max_length=12, unique=True),
        ),
    ]
