# Generated by Django 4.2.13 on 2024-08-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='7bb8d7394096', editable=False, max_length=12, unique=True),
        ),
    ]
