# Generated by Django 4.2.13 on 2024-08-19 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_order_order_number_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='8158a933804a', editable=False, max_length=12, unique=True),
        ),
        migrations.CreateModel(
            name='OrderCustomerProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ordercustomer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
            options={
                'unique_together': {('order_customer', 'product')},
            },
        ),
        migrations.CreateModel(
            name='CustomerProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ordercustomer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
            options={
                'unique_together': {('order_customer', 'product')},
            },
        ),
    ]
