# Generated by Django 4.2.13 on 2024-08-19 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_alter_order_order_number'),
    ]

    operations = [
    ]
