# Generated by Django 4.2.13 on 2024-08-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_lot_vendor_order_is_submitted_alter_product_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='build_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
