# Generated by Django 4.2.13 on 2024-08-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_lot_date_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='date_received',
            field=models.DateField(auto_now_add=True),
        ),
    ]
