# Generated by Django 4.2.13 on 2024-08-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_alter_lot_date_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='lot_number',
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
    ]
